# This file was generated by GoReleaser. DO NOT EDIT.
class Hellohomebrew < Formula
  desc "BEW 2.5 - Homebrew Hello World"
  homepage "https://github.com/Gaoyagi/homebrew-hellohomebrew"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Gaoyagi/hellohomebrew/releases/download/v1.0.1/hellohomebrew_1.0.1_macOS-64bit.tar.gz"
    sha256 "6b5e38ee0a59ed2d84cc07b26e51df42ae711156562c4774c4762d0e269b08db"
  elsif OS.linux?
  end

  def install
    bin.install "hellohomebrew"
  end
end
